AB#107343: Filter UI
decsys/decsys pull request #243
Opened 2023-07-10 12:29 UTC by MoizIqbal97

Created a UI for filtering and sorting
Refactored components

<img width="1436" alt="image" src="https://github.com/decsys/decsys/assets/90258816/50066e56-0243-4ff3-9b39-cfc863e20cf3">

2023-07-12 09:56 UTC, AndyRae requested changes

2023-07-12 09:56 UTC, AndyRae commented on app/client-app/src/app/pages/Wordlist/components/WordlistSortingAndFiltering.jsx
> +      {Object.keys(data).length && (
```suggestion
      {Object.keys(data).length > 0 && (
```
Conditional rendering on .length can end up rendering "0" if data is empty, as it's still truthy.

2023-07-12 10:33 UTC, blargly approved these changes

2023-07-12 12:47 UTC, AndyRae approved these changes

2023-07-13 09:49 UTC, Dev-Akashili approved these changes

2023-07-13 10:14 UTC, merged