AB#113972: Mulitiple filters
decsys/decsys pull request #244
Opened 2023-07-14 10:55 UTC by MoizIqbal97

This PR update supports multiple filtering to take place

- _getFilteredLookup_ update to handle filterer being a function or a string
- _filterConfig_ state initialised to an objects
- New fitlerers
  1. _exclusionStateMatches_: This filterer filters words based on whether they are excluded or included.
  2. _typeMatches_: This filterer shows words if their type matches a given filter.
  3. _minLengthIsMet_, _maxLengthIsNotExceeded_: These filterers filter words depending on whether their length falls within a given range.

- Documents updates
- Unit tests for _getFilteredLookup_

Example shows words that are adjective and excluded (blocked)
![Screenshot 2023-07-14 at 09 45 37](https://github.com/decsys/decsys/assets/90258816/0dba0247-8fed-497f-a1bb-efdc8e99cd0d)

2023-07-14 12:12 UTC, beforan requested changes

2023-07-14 12:12 UTC, beforan commented on app/client-app/src/app/pages/Wordlist/components/hooks/useWordlistSortingAndFiltering.js
> +    minLengthIsMet: (value, filter) => value.word.length >= filter,
I think you can merge minLength and maxLength into a single filter that checks the value is between both values

2023-07-14 12:12 UTC, beforan commented on app/client-app/src/hooks/useSortingAndFiltering.js
>  const storageKeyPrefix = "sargassure.sorting";
```suggestion
const storageKeyPrefix = "decsys.sorting";
```

2023-07-17 10:56 UTC, beforan approved these changes

2023-07-17 10:59 UTC, Jivanam approved these changes

2023-07-17 11:03 UTC, AndyRae approved these changes

2023-07-17 11:09 UTC, merged

2023-07-17 11:13 UTC, blargly approved these changes