AB#133590: Webhook Notification
decsys/decsys pull request #271
Opened 2023-10-30 11:53 UTC by MoizIqbal97

Increment notification when webhook gets triggere

2023-10-30 12:00 UTC, beforan requested changes

2023-10-30 12:00 UTC, beforan commented on app/client-app/src/components/shared/SurveyPage.jsx
> +            <WebhookCounter />
have this conditionally render on when `webhookCount != null`? that should fulfill it only showing in preview mode (which passes a numeric count) vs  real survey (which doesn't)?

2023-10-30 13:39 UTC, beforan approved these changes

2023-10-31 10:53 UTC, Dev-Akashili approved these changes

2023-10-31 10:59 UTC, merged